version: '3.1'

services:
  db:
    image: postgres
    container_name: qual_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5455:5432"
  redis:
    image: redis:latest
    container_name: qual_rd
    restart: always
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=secret
      - REDIS_PORT=6379
      - REDIS_DATABASES=0
  jaeger:
    image: jaegertracing/all-in-one
    container_name: qual_jg
    ports:
      - "14268:14268"
      - "16686:16686"
  rabbit:
    container_name: qual_rb
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5673:5672"
      - "15673:15672"